<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="/application/view/js/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
<script src="/application/view/js/popper.min.js" crossorigin="anonymous"></script>
<script src="/application/view/js/bootstrap.min.js" crossorigin="anonymous"></script>

<div id="push"></div>
</div>
</body>
<div class="card-footer">
    <div class="row align-items-end">
        <div class="col text-left">
            <a href="#"><small>反馈</small></a>

            <!-- QQ -->
            <a target="_blank" href="http://sighttp.qq.com/authd?IDKEY=1dd3481ea3dc196e7636d237625fe3f88eec701875639f2e"><img border="0"  src="http://wpa.qq.com/imgd?IDKEY=1dd3481ea3dc196e7636d237625fe3f88eec701875639f2e&pic=52" alt="llmmoe : 1837141234" title="llmmoe : 1837141234"/></a>

            <!-- WeiXin -->
            <a href="#" data-toggle="modal" data-target="#exampleModalCenter">
                <img title="六六 : ZoE0079" class="img-circle" height="20px" src="\application\view\images\wx-logo.jpg" />
            </a>
            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">六六</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <img class="img-fluid" src="\application\view\images\my-wx.jpg">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col text-center">
            <small>© 2018 甘溪镇党政办</small>
        </div>
        <div class="col text-right">
            <small> beta 0.1 </small>
        </div>
    </div>
</div>
</html>