<div class="container">
    <div class="page-header">
    <div class="row">

        <div class="col-sm-auto">
            <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                <div class="card-header">标签1</div>
                <div class="card-body">
                    <h4 class="card-title">计划项目</h4>
                    <p class="card-text">功能实现</p>
                    <ul>
                        <ul>
                            <li>
                                <del>人员信息管理</del>
                            </li>
                        </ul>
                        <li>
                            分类选人，<del>拨号</del>
                        </li>
                        <li>
                            文件归档（这个简单）
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-sm-auto">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                <div class="card-header">标签2</div>
                <div class="card-body">
                    <h4 class="card-title">计划项目</h4>
                    <p class="card-text">功能实现</p>
                    <h4>数据录入</h4>
                    <p>数据补充</p>
                    <ol>
                        <li>人员信息差简历、职务</li>
                        <li>请假统计</li>
                    </ol>
                </div>
            </div>
        </div>

    </div>
    </div>
</div>
<div id="push"></div>