<div class="container-fluid">
    <p class="bs-component">
        <button id="button" class="btn btn-primary" onclick="window.location.href='?mod=incoming&act=add'">添加</button>
    </p>

    <div class="row">

        <div class="col-lg-auto">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>日期</th>
                    <th>时间</th>
                    <th>来电单位</th>
                    <th>号码</th>
                    <th>事件</th>
                    <th>接收</th>
                    <th>处理</th>
                    <th>情况</th>
                    <th></th>
                </tr>
                </thead>


                <tbody>
                <?php foreach($incomingList as $k => $v):?>
                <tr<?php if(empty($v['state'])):?> class="table-warning"<?php endif;?>>
                    <td><?php echo $v['date']?></td>
                    <td><?php $time = explode(':', $v['time']);echo $time[0].":".$time[1];?></td>
                    <td><?php echo $v['nation']?></td>
                    <td><?php echo $v['tel']?></td>
                    <td width="600px"><?php echo $v['case']?></td>
                    <td><?php echo $v['receive']?></td>
                    <td><?php echo $v['handle']?></td>
                    <td width="200px"><?php echo $v['state']?></td>
                    <td class="actions">
                        <a href="?mod=incoming&act=update&id=<?php echo $v['id']?>"><span class="badge badge-primary">修改</span></a>&nbsp;&nbsp;
                        <a href="?mod=incoming&act=del&id=<?php echo $v['id']?>"><span class="badge badge-danger">删除</span></a>
                    </td>
                </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>

    </div>

</div>

