<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Coderthemes">

        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">
        <!-- App title -->
        <title><?php _print($pageInfo['title']);?></title>

        <!-- App css -->
        <link href="<?php echo viewUrl()?>assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo viewUrl()?>assets/css/core.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo viewUrl()?>assets/css/components.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo viewUrl()?>assets/css/icons.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo viewUrl()?>assets/css/pages.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo viewUrl()?>assets/css/menu.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo viewUrl()?>assets/css/responsive.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="<?php echo viewUrl()?>assets/js/html5shiv.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/respond.min.js"></script>
        <![endif]-->

        <script src="<?php echo viewUrl()?>assets/js/modernizr.min.js"></script>

    </head>


    <body class="bg-transparent">

        <!-- HOME -->
        <section>
            <div class="container-alt">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="wrapper-page">

                            <div class="m-t-40 account-pages">
                                <div class="text-center account-logo-box">
                                    <h2 class="text-uppercase">
                                        <a href="<?php echo base_url()?>" class="text-success">
                                            <span><img src="<?php echo viewUrl()?>assets/images/logo.png" alt="" height="36"></span>
                                        </a>
                                    </h2>
                                    <!--<h4 class="text-uppercase font-bold m-b-0">Sign In</h4>-->
                                </div>
                                <div class="account-content">
                                    <form class="form-horizontal" action="<?php echo base_url()?>?mod=login&act=login">

                                        <div class="form-group ">
                                            <div class="col-xs-12">
                                                <input class="form-control" type="text" required="" placeholder="用户名">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-xs-12">
                                                <input class="form-control" type="password" required="" placeholder="密码">
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <div class="col-xs-12">
                                                <div class="checkbox checkbox-success">
                                                    <input id="checkbox-signup" type="checkbox">
                                                    <label for="checkbox-signup">
                                                        授权这台电脑？
                                                    </label>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="form-group text-center m-t-30">
                                            <div class="col-sm-12">
                                                <a href="page-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> 忘记密码？ </a>
                                            </div>
                                        </div>

                                        <div class="form-group account-btn text-center m-t-10">
                                            <div class="col-xs-12">
                                                <button class="btn w-md btn-bordered btn-danger waves-effect waves-light" type="submit"> 登 陆 </button>
                                            </div>
                                        </div>

                                    </form>

                                    <div class="clearfix"></div>

                                </div>
                            </div>
                            <!-- end card-box-->


                            <div class="row m-t-50">
                                <div class="col-sm-12 text-center">
                                    <p class="text-muted">没有账号？ <a href="page-register.html" class="text-primary m-l-5"><b>注册</b></a></p>
                                </div>
                            </div>

                        </div>
                        <!-- end wrapper -->

                    </div>
                </div>
            </div>
          </section>
          <!-- END HOME -->

        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="<?php echo viewUrl()?>assets/js/jquery.min.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/bootstrap.min.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/detect.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/fastclick.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/jquery.blockUI.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/waves.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/jquery.slimscroll.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/jquery.scrollTo.min.js"></script>

        <!-- App js -->
        <script src="<?php echo viewUrl()?>assets/js/jquery.core.js"></script>
        <script src="<?php echo viewUrl()?>assets/js/jquery.app.js"></script>

    </body>
</html>