<div class="container">
    <div class="col-md-auto">

        <form class="form-horizontal" role="form" method="post" action="?mod=incoming&act=insert<?php if(isset($value['id'])):?>&id=<?php echo $value['id'];endif;?>">
            <div class="form-group">
                <h2 class="text-center"><?php echo $info['name']; ?></h2>
                <label class="col-md-auto">日期</label>
                <div class="col-sm-4">
                    <input name="date" class="form-control" type="text"
                           value="<?php
                           if(isset($value)){
                               echo $value['date'];
                           }elseif(isset($error['date'])) {
                               echo $error['date'];
                           }else{
                               echo date('Y-m-d');
                           }
                           ?>">
                    <?php if(isset($error['dateInfo'])):?>
                        <div class="alert alert-danger"><?php echo $error['dateInfo'];?></div>
                    <?php endif;?>
                </div>
            </div>

            <div class="form-group <?php if(isset($error['timeInfo'])):?>has-error has-feedback<?php endif;?>">
                <label class="col-md-2 control-label">时间</label>
                <div class="col-sm-3">
                    <div class="input-group">
                        <input name="time" id="timepicker2" class="form-control" type="text"
                               value="<?php
                               if(isset($value)){
                                   echo $value['time'];
                               }elseif(isset($error['time'])) {
                                   echo $error['time'];
                               }else{
                                   echo date('H:i');
                               } ?>">
                        <?php if(isset($error['timeInfo'])):?>
                            <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                            <div class="alert alert-danger"><?php echo $error['timeInfo'];?></div>
                        <?php endif;?>
                        <span class="input-group-addon"><i class="mdi mdi-clock"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group <?php if(isset($error['nationInfo'])):?>has-error has-feedback<?php endif;?>">
                <label class="col-md-2 control-label">来电单位</label>
                <div class="col-md-4">
                    <input name="nation" class="form-control" placeholder="单位" type="text"
                           value="<?php if(isset($value)){
                               echo $value['nation'];
                           }elseif(isset($error['nation'])) {
                               echo $error['nation'];
                           }?>">
                    <?php if(isset($error['nationInfo'])):?>
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                        <div class="alert alert-danger"><?php echo $error['nationInfo'];?></div>
                    <?php endif;?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">号码</label>
                <div class="col-md-4">
                    <input name="tel" class="form-control" placeholder="电话" type="text"
                           value="<?php if(isset($value)){
                               echo $value['tel'];
                           }elseif(isset($error['tel'])){
                               echo $error['tel'];
                           }?>">
                </div>
            </div>

            <div class="form-group <?php if(isset($error['caseInfo'])):?>has-error has-feedback<?php endif;?>">
                <label class="col-md-2 control-label">事件</label>
                <div class="col-md-10">
                    <textarea name="case" class="form-control" rows="5"><?php
                        if(isset($value)){
                            echo $value['case'];
                        }elseif(isset($error['case'])){
                            echo $error['case'];
                        }?></textarea>
                    <?php if(isset($error['caseInfo'])):?>
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                        <div class="alert alert-danger"><?php echo $error['caseInfo'];?></div>
                    <?php endif;?>
                </div>
            </div>

            <div class="form-group <?php if(isset($error['receiveInfo'])):?>has-error has-feedback<?php endif;?>">
                <label class="col-md-2 control-label">接收人员</label>
                <div class="col-md-2">
                    <input name="receive" class="form-control" placeholder="姓名" type="text"
                           value="<?php if(isset($value)){
                               echo $value['receive'];
                           }elseif(isset($error['receive'])){
                               echo $error['receive'];
                           }?>">
                    <?php if(isset($error['receiveInfo'])):?>
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                        <div class="alert alert-danger"><?php echo $error['receiveInfo'];?></div>
                    <?php endif;?>
                </div>
            </div>

            <div class="form-group <?php if(isset($error['handleInfo'])):?>has-error has-feedback<?php endif;?>">
                <label class="col-md-2 control-label" for="example-email">处理人员</label>
                <div class="col-md-2">
                    <input name="handle" class="form-control" placeholder="姓名" type="text"
                           value="<?php if(isset($value)){
                               echo $value['handle'];
                           }elseif(isset($error['handle'])){
                               echo $error['handle'];
                           }?>">
                    <?php if(isset($error['handleInfo'])):?>
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                        <div class="alert alert-danger"><?php echo $error['handleInfo'];?></div>
                    <?php endif;?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="example-email">处理情况</label>
                <div class="col-md-10">
                    <textarea name="state" class="form-control" rows="5"><?php if(isset($value)){
                            echo $value['state'];
                        }elseif(isset($error['state'])){
                            echo $error['state'];
                        }?></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="example-email"></label>
                <div class="col-md-10">
                    <button type="submit" class="btn btn-primary waves-effect w-md waves-light m-b-5">提交</button>
                </div>
            </div>
        </form>

    </div>
</div>

<form
    action="?mod=staff&act=update_info<?php echo "&id=" . $info['id'] ?>"
    method="post">
    <h2 align="center"><?php echo $info['name']; ?></h2>
    <?php if (!empty($info['photo'])) { ?><img src="<?php echo $info['photo'] ?>" /><?php } ?>
    <table id="info" align="center">
    <tr>
            <td class="right" width="40%">电话</td>
            <td><input type="text" name="phone"
                value="<?php echo $info['phone'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">短号</td>
            <td><input type="text" name="short_phone"
                value="<?php echo $info['short_phone'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">性别</td>
            <td><select name="is_male">
                    <option value="3">--</option>
                    <option value="1"
                        <?php if ($info['is_male'] == 1) echo 'selected="selected"' ?>>男</option>
                    <option value="0"
                        <?php if ($info['is_male'] == 0) echo 'selected="selected"' ?>>女</option>
            </select></td>
        </tr>
        <tr>
            <td class="right">民族</td>
            <td><input type="text" name="nation"
                value="<?php echo $info['nation'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">短号</td>
            <td><input type="text" name="card_id"
                value="<?php echo $info['card_id'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">生日</td>
            <td><input type="text" name="birthday"
                value="<?php echo $info['birthday'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">参加工作时间</td>
            <td><input type="text" name="date_on_job"
                value="<?php echo $info['date_on_job'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">政治面貌</td>
            <td><select name="political_status">
                    <option value="">--</option>
                    <option value="党员"
                        <?php if ($info['political_status'] == "党员") echo 'selected="selected"' ?>>党员</option>
                    <option value="群众"
                        <?php if ($info['political_status'] == "群众") echo 'selected="selected"' ?>>群众</option>
            </select></td>
        </tr>
        <tr>
            <td class="right">入党时间</td>
            <td><input type="text" name="date_in_political"
                value="<?php echo $info['date_in_political'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">全日制学历</td>
            <td><input type="text" name="education"
                value="<?php echo $info['education'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">全日制大学</td>
            <td><input type="text" name="university"
                value="<?php echo $info['university'] ?>" size="45" /></td>
        </tr>
        <tr>
            <td class="right">在职学历</td>
            <td><input type="text" name="education_in_service"
                value="<?php echo $info['education_in_service'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">在职大学</td>
            <td><input type="text" name="university_in_service"
                value="<?php echo $info['university_in_service'] ?>" /></td>
        </tr>
        <tr>
            <td class="right">身份</td>
            <td><select name="status">
                    <option value="">--</option>
                    <option value="行政"
                        <?php if ($info['status'] == "行政") echo 'selected="selected"' ?>>行政</option>
                    <option value="事业"
                        <?php if ($info['status'] == "事业") echo 'selected="selected"' ?>>事业</option>
            </select></td>
        </tr>
        <tr>
            <td colspan="2">简历<br /> <textarea name="resume" rows="10"
                    cols="100%"><?php echo $info['resume'] ?></textarea>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <button class="button button-primary button-pill button-small"
                    type="submit">更 新</button>
                <button class="button button-caution button-pill button-small"
                    onclick="window.location.go(-1)">取 消</button>
            </td>
            <td></td>
        </tr>
    </table>
</form>
