<html>
<head>
<meta charset="utf-8">
<script src="<?php echo VIEW_DIR;?>js/jquery-3.2.1.min.js"></script>
<?php if(!empty($ajax)) echo $ajax; ?>
    </head>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.b01').click(function(){
                var htmlobj = $.ajax({
                    type:"POST",
                    url:"/user.txt",
                    dataType:"json",
                    async:false,
                });
                // alert(htmlobj);
                $('.myDiv').html(htmlobj.responseText);
            });
        });
    </script>
    <body>
        <p class="b01">test</p>
        <div class="myDiv"></div>
    </body>
</html>
